services:
  - type: web
    name: fonlineweb
    env: docker
    dockerfilePath: server/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
